version: '3'

services:
  user-service:
    depends_on:
      - mongo
    network_mode: host
    image:  wdm2019akka/service-runner
    command: u -Dakka.cluster.seed-nodes.0=akka.tcp://flocka-user@${SEED0_IP}:2551  -Dakka.remote.netty.tcp.hostname=${MY_IP} -Dakka.remote.netty.tcp.port=2551

  stock-service:
    depends_on:
      - mongo
    network_mode: host
    image:  wdm2019akka/service-runner
    command: s -Dakka.cluster.seed-nodes.0=akka.tcp://flocka-stock@${SEED0_IP}:2561  -Dakka.remote.netty.tcp.hostname=${MY_IP} -Dakka.remote.netty.tcp.port=2561

  order-service:
    depends_on:
      - mongo
    network_mode: host
    image:  wdm2019akka/service-runner
    command: o -Dakka.cluster.seed-nodes.0=akka.tcp://flocka-order@${SEED0_IP}:2571  -Dakka.remote.netty.tcp.hostname=${MY_IP} -Dakka.remote.netty.tcp.port=2571

  payment-service:
    depends_on:
      - mongo
    network_mode: host
    image:  wdm2019akka/service-runner
    command: p -Dakka.cluster.seed-nodes.0=akka.tcp://flocka-payment@${SEED0_IP}:2581  -Dakka.remote.netty.tcp.hostname=${MY_IP} -Dakka.remote.netty.tcp.port=2581

  mongo:
    network_mode: host
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
